In [62]:
import pandas as pd
import numpy as np
from json import loads, dumps

In [54]:
table = pd.read_csv("/Users/farhadghassemi/Library/CloudStorage/OneDrive-Personal/Courses/Stanford/Conversational Virtual Assistant with Deep Learning/Project/Results/result_wikipedia_model_wikidata_compmix_dev_set_gpt_domain_not_passed_generic_examples_from_WWQ_compmix_max_entities_4_extended_prompt.csv")
table.sort_values(by=['question_id'], inplace=True)
table = table.reset_index()

In [55]:
table.head()

,index,question_id,domain,question,gold_entity_id,gold_entity_label,predicted_entity_id,predicted_entity_label,predicted_entity_score
0,1510,4966,books,Which is the first book of the book series Div...,Q16514101,Divergent,NaN,NaN,NaN
1,1509,4966,books,Which is the first book of the book series Div...,NaN,NaN,Q627192,Divergent (novel),0.4737
2,1508,4966,books,Which is the first book of the book series Div...,NaN,NaN,Q328212,Veronica Roth,0.9756
3,2309,4967,books,Who is the author of the book Divergent (novel)?,NaN,NaN,Q328212,Veronica Roth,0.9756
4,2308,4967,books,Who is the author of the book Divergent (novel)?,Q627192,Divergent (novel),Q627192,Divergent (novel),0.4737

In [42]:
table['predicted_entities'] = [{key: val} for key, val in zip(table.Stage_Name, table.Metrics)]

table['predicted_entities'] = table[['predicted_entity_id', 'predicted_entity_label']].to_dict()
table['gold_entities'] = table[['gold_entity_id', 'gold_entity_label']].values.tolist()
table.drop(['gold_entity_id', 'gold_entity_label', 'predicted_entity_id', 'predicted_entity_label', 'predicted_entity_score'], axis=1, inplace=True)

In [43]:
table.head()

,question_id,domain,question,predicted_entities,gold_entities
0,6470,books,What was Johann Morgenstern's profession?,NaN,"[Q67149, Johann Karl Simon Morgenstern]"
1,5136,tvseries,Who was the voice actor for Meg Griffin in Fam...,NaN,"[Q908772, Meg Griffin]"
2,5136,tvseries,Who was the voice actor for Meg Griffin in Fam...,NaN,"[Q5930, Family Guy]"
3,5136,tvseries,Who was the voice actor for Meg Griffin in Fam...,NaN,"[nan, nan]"
4,5835,soccer,What is the complete name of the player Bebé?,NaN,"[Q299450, Bebé]"

In [38]:
table2 = table.groupby("question_id").agg({'domain': 'first', 'question': 'first', 'predicted_entities': lambda x: list(x), 'gold_entities': lambda x: list(x)})
table2['gold_entities'] = table2['gold_entities'].apply(lambda x: [xi for xi in x if not pd.isna(xi[0])])
table2['predicted_entities'] = table2['predicted_entities'].apply(lambda x: [xi for xi in x if not pd.isna(xi[0])])

In [39]:
table2.head()

,domain,question,predicted_entities,gold_entities
question_id,,,,
4966,books,Which is the first book of the book series Div...,"[[Q328212, Veronica Roth], [Q627192, Divergent...","[[Q16514101, Divergent]]"
4967,books,Who is the author of the book Divergent (novel)?,"[[Q627192, Divergent (novel)], [Q328212, Veron...","[[Q627192, Divergent (novel)]]"
4968,books,What is the date of birth of the Divergent's a...,"[[Q328212, Veronica Roth]]","[[Q328212, Veronica Roth], [Q627192, Divergent]]"
4969,books,Which is the second book of the series Divergent?,[],"[[Q16514101, Divergent]]"
4970,books,What is the publication date of the Insurgent ...,"[[Q5918512, Insurgent (novel)]]","[[Q5918512, Insurgent (novel)]]"

In [64]:
result = table2.to_json("/Users/farhadghassemi/Library/CloudStorage/OneDrive-Personal/Courses/Stanford/Conversational Virtual Assistant with Deep Learning/Project/Results/result_wikipedia_model_wikidata_compmix_dev_set_gpt_domain_not_passed_generic_examples_from_WWQ_compmix_max_entities_4_extended_prompt.json", orient="records", indent=3)